version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:17.5.0
  environment:
    DEV_TENANT_NAME: dev
    PROD_TENANT_NAME: prod
    QA_TENANT_NAME: qa
    PREPROD_TENANT_NAME: snp
    RELEASE_BUCKET_NAME: "duploservices-default-serverless-128329325849"

jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install serverless
          command: sudo npm install -g serverless
      - run:
          name: Install other dependencies
          command: npm install
      - run:
          name: Build
          command: serverless package --stage dev --package ./build
#      - run:
#          name: Run tests
#          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker:
          version: 19.03.13
        
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish_to_s3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install AWS CLI
          command: |
            source ./.circleci/duplo_utils.sh
            install_dependencies
      - run:
          name: Publish to s3 bucket
          command: |
            tag=$(git rev-parse HEAD)
            source ./.circleci/duplo_utils.sh
            with_aws aws s3 cp ./build/*.zip s3://${BUCKET_NAME}/serverless/${tag}
      - run:
          name: Deploy to Dev
          command: |
            tag=$(git rev-parse HEAD)
            source ./.circleci/duplo_utils.sh
            update_lambda_functions $tag
workflows:
  version: 2.1
  build_test_publish:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /^v.*/
      - publish_to_s3:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/